### PR TITLE
add release action

### PR DESCRIPTION
**Pull request by jakobhellermann**
Adds a `release.yml` github actions workflow that builds the server binary and extension for every target listed in https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions.

The action runs on new git tags, and creates a release with all the binaries and vsix, and calls `vsce publish`.
You'll need to add a `VSCE_PAT` github secret ([how to get access token](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token)) and add a `publisher` field to the package.json.

- add png version of icon
- change `extension.ts` to look for bundled executable first, falls back to `typst-lsp[.exe]` (could also be configurable via vscode settings)
- add LICENSE file and package.json properties to `addons/vscode`
- add `esbuild` for bundling and change package.json scripts
  - `npm run package` builds `.vsix`, bundles using esbuild minified
  - `npm run compile` bundles using esbuild with source maps
  - `npm run check` runs `tsc` to check typescript
  - `npm run lint/lint-fix` as before

If you'd like to have anything changed let me know :)

### CODE REVIEW

**Comment by nvarner** [comment]
I don't have time to fully review this right now, but this looks great! I'll get to it as soon as I can. My biggest concern is actually the name of the project; I'd like to make sure it's okay to call this "Typst LSP" and not "LSP for Typst" or something similar (to avoid looking official when we're not).

**Comment by beeb** [comment]
Suggesting adding the following to speed up builds:

Incremental builds end up being slower in CI because there is overhead and there wasn't a previous build to base upon.

```
env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_INCREMENTAL: '0'
```

**Comment by beeb** [comment]
Oh awesome, I didn't know! Never mind my comment then :)

**Comment by nvarner** [comment]
This looks good. I'll probably set up a VS Code task like you suggested, so everything "just works".

**Comment by beeb** [comment]
I think the alpine build fails because @vscode/vsce is not installed

**Pull request merged**
