### PR TITLE
Add Rust Analyzer in the install instructions

### PR DESCRIPTION
**Pull request by CGMossa**
UPDATE: This PR now *specifies* the dependence on Rust Analyzer through the install instructions.

Currently, installing the extension for developers, depends on Rust Analyzer.
That is due to `"type": "cargo"` is a construction from rust-analyzer. 

~~Instead, this just invokes cargo as a shell command.~~

### CODE REVIEW

**Comment by nvarner** [comment]
Is this a common problem? My understanding is that effectively all Rust developers on VS Code use `rust-analyzer`.

**Comment by CGMossa** [comment]
Either this change or the install instructions should contain rust analyzer.
A user was having issues.. They are still having them but I solved this one.

**Comment by nvarner** [comment]
Recommending installing `rust-analyzer` would be better, since Rust development without it would be difficult.

As an aside, do you have a link to where someone was having trouble? I don't think I saw it, but I'll offer help if I'm able, and seeing what's hard can drive development.

**Comment by CGMossa** [comment]
I'll make that PR later.
https://discord.com/channels/1054443721975922748/1089255512228499516/1089415250740260915

**Comment by CGMossa** [comment]
What's the benefit of having the cargo build task depend on rust analyzer rather than this?

**Comment by nvarner** [comment]
Oh, I see; it's not possible to even run the extension without the RA plugin.

However, using it gives us [problem matchers](https://michaelheap.com/getting-started-problem-matchers/). In general, it should usually provide better editor integration than a command. It probably also works better in strange environments. For instance, I can see someone alias an unusual command to `cargo`, or leave it out of their path, or something else unexpected. The RA task should still work, but the command line would not.

I think it's still best to pivot this PR into recommending installing RA. It would also be okay if there's an easy way to add the RA problem matcher to the command line task without depending on RA, and the task is renamed to indicate that it's part of the build process for testing the extension, not a recommended way of building the LSP.

**Comment by nvarner** [comment]
And thanks for providing support!

**Comment by CGMossa** [comment]
Thanks! And no problem.. Unfortunately collaboration requires that someone gets educated sometimes.

**Comment by CGMossa** [comment]
@nvarner It should be ready now.

**Comment by CGMossa** [comment]
Perfect suggestion; I've added it now.

**Comment by nvarner** [comment]
Thanks! This will help new users.

**Pull request merged**
