### PR TITLE
adds formatter capabilities using typstfmt

### LINKED ISSUE #204: Does it support format code by typst-fmt(typstfmt)?
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

<https://github.com/astrale-sharp/typstfmt>

### PR DESCRIPTION
**Pull request by astrale-sharp**
Closes #204 
The formatter is globally decent but still experimental, how should I communicate that with the users?

### CODE REVIEW

**Comment by nvarner** [comment]
Probably, the best option is to make the formatter a disabled-by-default configuration option with a warning that it is experimental. It can be documented in the README (until I get better docs set up) to let users know it's there.

**Comment by astrale-sharp** [comment]
bug with the lsp giving a different formatting result

**Comment by astrale-sharp** [comment]
In another PR i could add the option to read the formatter config file (and even create it automatically)

**Comment by astrale-sharp** [comment]
I'm not sure if i can make cargo deny happy

**Review by nvarner — COMMENTED** [review]
The best way to appease cargo deny would be to publish `typstfmt` on crates.io, but that's hard given Typst. Since we'll have to use a git dependency:

1. To ensure that changes in `typstfmt` don't unexpectedly break `typst-lsp`, include a tag or commit hash in the `Cargo.toml`. Tags are better, but commit hashes are okay for now, especially since it's explicitly experimental. Unless the `hash` tag does something I'm not familiar with, [you'll probably want the `rev` tag](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).
2. To actually make cargo deny stop complaining, [include an `allow-git` entry in `deny.toml`](https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html#the-allow-git-field-optional).

**Comment by astrale-sharp** [comment]
Should be good?

**Comment by nvarner** [comment]
The one thing I see is the way the formatter is disabled. Because it's always registered as available, attempting to format without enabling the formatter causes an error message. For example, in my VS Code setup, all files automatically format on save when a formatter is available for them, which means I would get an error popup whenever I save a Typst file.

The way to fix this is with dynamic registration, which is a bit of a pain to set up. I just went through and did it since I've had to do it before. I was about to PR the changes (see the astrale-sharp-typstfmt branch), but I seem to have inadvertently done something like a rebase and included other commits along with the change I was trying to make.

I'll try to address that soon. If you can tell that it's fine before then, feel free to pull those changes into your branch.

**Comment by nvarner** [comment]
Looks like I did rebase, but it's rebased properly, so should be okay. [My PR to your branch](https://github.com/astrale-sharp/typst-lsp/pull/1) adds dynamic registration and performs the rebase.

**Comment by astrale-sharp** [comment]
Lovely thank you!

**Comment by astrale-sharp** [comment]
merged!

**Comment by nvarner** [comment]
I plan to merge this once I get a release out for #254. Thanks for the contribution, and best of luck with the continuing development of `typstfmt`.

**Comment by astrale-sharp** [comment]
Thank you very much! :D

Should I open a pull request everytime typstfmt could be bumped?

**Comment by nvarner** [comment]
That's probably the best approach for now. If you get to the point where `typst-fmt` has tags/releases (I'm not sure which exactly triggers this), @dependabot seems to notice and will make those PRs automatically, like it did here for [`typst-library`](https://github.com/nvarner/typst-lsp/pull/191).

**Pull request merged**
