### PR TITLE
[Feature] "Show PDF" button

### PR DESCRIPTION
**Pull request by dvdvgt**
This PR is in response to #69.

# Discussion

I am not really happy how the file extension/type is currently manually changed from `.typ` to `.pdf`. I'll happily implement something more robust if somebody has a recommendation.

### CODE REVIEW

**Comment by nvarner** [comment]
At present, I think the filename conversion is okay. Doing better depends on finding a good way to decide which files get compiled into PDFs and what those PDFs should be called, which hasn't happened yet.

**Comment by nvarner** [comment]
@dvdvgt can you fix the failing lint? This will be ready to merge after that.

**Comment by dvdvgt** [comment]
Should be good now. Feel free to squash all commits into one.

**Comment by nvarner** [comment]
Oops, that latest failure might have been my fault; I needed an extra feature in a dependency, and I force pushed while preparing a PR to upstream the changes. My changes were upstreamed but not yet released, so it's okay to keep the `elsa` Git dependency. To fix the changed Git commit hash, can you try `cargo update elsa`? I think that will resolve it.

**Pull request merged**
