### PR TITLE
fix: path resolution on Windows

### PR DESCRIPTION
**Pull request by beeb**
Closes https://github.com/nvarner/typst-lsp/issues/22

### CODE REVIEW

**Comment by CGMossa** [comment]
Can I ask about something else? Have you successfully installed the extension on windows? I need
to add `.exe` to this line to just install it https://github.com/nvarner/typst-lsp/blob/893b324f14b0d2f35debbea8312798a7f79eb7a5/.vscode/tasks.json#LL35.

I'm using this PR.

**Comment by beeb** [comment]
@CGMossa here is how I fixed it https://github.com/nvarner/typst-lsp/blob/66d361f66f26621bccb07e06ae79371c8a0fb3ec/.vscode/tasks.json

It's part of my latest PR that should get merged hopefully soon

**Comment by CGMossa** [comment]
That's very smart!

**Comment by CGMossa** [comment]
Just to let you know, I also think we should set `CARGO_TARGET_DIR` should be set, as to avoid if people have a `.cargo/config.toml` file where there is one common target directory for all rust artefacts (to avoid massive bloat, etc.)

The best thing would of course be to be able to acquire that path somehow.. But I'm not sure that's possible :(

**Comment by beeb** [comment]
@CGMossa this is not really the place to discuss this, but cargo is only relevant to developers of the LSP at the moment, not sure it has relevance in the bigger scheme of things. Maybe open an issue if you want to describe further why this is needed.

**Comment by CGMossa** [comment]
Yes, you're right!

I can confirm that with this, the extension works on (my) Windows.

**Comment by nvarner** [comment]
Looks good. Thank you!

**Comment by nvarner** [comment]
And @CGMossa, can you open an issue with more details about the `CARGO_TARGET_DIR` issue? I'm not sure I entirely understand the problem, and an issue is the best place to get it figured out.

**Pull request merged**
