### PR TITLE
Add support for document and workspace symbols

### PR DESCRIPTION
**Pull request by beeb**
This PR adds support for document and workspace symbols.

On initialisation and if we have a `root_dir` (workspace) or a collection of `workspace_folders`, the directories are recursively walked to register all `.typ` files as being part of the workspace.

Regarding symbols, the following items are now included in the symbols listing:

- Labels
- Variables
- Functions
- Headings

I had to get creative with the "symbol type" for labels and headings, these can be discussed and changed if necessary. At the moment, headings are considered as "NAMESPACE" and labels are "CONSTANT". This is mainly to have a visual differentiation in the UI.

If you think other nodes should be considered for addition in this list, feel free to comment or open an issue.

Closes https://github.com/nvarner/typst-lsp/issues/59

### CODE REVIEW

**Comment by nvarner** [comment]
After the refactor, this PR will need to be rebased in order to be merged.

**Comment by beeb** [comment]
@nvarner trying to get familiar with the new structure now. Any pointers would be nice if you already thought about how to integrate my changes.

**Comment by beeb** [comment]
Not even going to try to solve merge conflicts, I started a new branch here https://github.com/beeb/typst-lsp/tree/document-symbols-new

Once I'm done porting over the changes I'll open a new PR and close this one.

**Comment by nvarner** [comment]
At a high level, the structure is:
- `src/workspace/` holds things "related to LSP workspaces". In practice, this means things "close to the OS", like Typst source code and resources
- `src/server/` holds LSP feature implementations. Each major component has its own file, and `lsp.rs` implements the LSP server functions
- `src/lsp_typst_boundary` holds conversions between internal types/LSP types and Typst types, the `World` implementation, and any other indirection to interface with Typst

In terms of structs,
- `TypstServer` implements the server functions (replacing `Backend`) and holds configuration and the `Workspace`.
- `WorkspaceWorld` implements `World` and is provided by `TypstServer`. Internally, it acquires a read lock on the `Workspace`.
- `Workspace` has most of the infrastructure to implement `World`

**Comment by nvarner** [comment]
Caching should be implemented now, and changes should move to their corresponding files. Eg. changes in `Backend` should go to changes in `TypstServer`. I don't think it will be too hard to port over, since the structure shouldn't have changed _too_ much.

**Comment by beeb** [comment]
Just to make sure, in the current state the server doesn't walk the workspace directory to get a reference to all typ files yet right? That I should again add into the initialization method.

**Comment by nvarner** [comment]
Correct, it's not doing that.

**Comment by beeb** [comment]
Almost getting there in that new branch but need to troubleshoot some problems.

**Comment by beeb** [comment]
Bugs are fixed, I'll merge a bit later.

**Comment by beeb** [comment]
This should be ready to merge

**Comment by nvarner** [comment]
Thank you! I'll review this soon.

**Comment by nvarner** [comment]
Looks good. Thank you!

**Pull request merged**
