### PR TITLE
Prefix the build command for discoverability

### PR DESCRIPTION
**Pull request by lvignoli**

### CODE REVIEW

**Comment by dvdvgt** [comment]
Hey, in my PR (#72) I added a new command and [used the `category` field](https://github.com/nvarner/typst-lsp/pull/72/files#diff-5e2f6584e91ab0a7d3d7cdd819146bb8164d779dda2c301466fd92542647a574R77) for prefixing the command description. This is my first time working with VSCode extension, but I think this might be preferable. Have a look [here](https://code.visualstudio.com/api/references/contribution-points#contributes.commands) at the docs.

**Comment by lvignoli** [comment]
Indeed, seems like the intended way!

**Comment by lvignoli** [comment]
I have fixed it, but using `Typst` in title case for the category name

**Comment by nvarner** [comment]
Thank you! Looks good.

**Pull request merged**
