### PR TITLE
match upstream typstfmt config file name

### PR DESCRIPTION
**Pull request by mtoohey31**
The typstfmt binary uses `typstfmt.toml` or `.typstfmt.toml` instead of `typstfmt-config.toml` (see the source code [here](https://github.com/astrale-sharp/typstfmt/blob/2093a920f64d947cb8d6ecc7846a2e4bf11b5216/src/main.rs#L18C7-L18C23)). This pull request makes it so we use the same names.

One question: would we want to also continue supporting `typstfmt-config.toml` for backwards compatibility? Or is it fine that we don't since formatting is experimental?

### CODE REVIEW

**Comment by astrale-sharp** [comment]
I think it's fine as long as we warn a bit in the release

**Comment by astrale-sharp** [comment]
I approve the changes btw

**Comment by mtoohey31** [comment]
> I think it's fine as long as we warn a bit in the release

Sounds good. Thanks for taking a look!

**Comment by Myriad-Dreamin** [comment]
LGTM. and we can make improvement about warning in a separated PR.

**Pull request merged**
